[build]
  publish = "public_html"  # Your frontend files are in public_html

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://eukexpress.onrender.com/api/:splat"
  status = 200
  force = false
